apiVersion: v1
kind: Service
metadata:
  name: stub-remote-executor
  labels:
    run: stub-remote-executor
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 8082
      name: h2c
  selector:
    run: stub-remote-executor
