# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: received_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("received_message.proto", :syntax => :proto2) do
    add_message "pckg_received_message.RequestAck" do
      optional :task_id, :string, 1
      optional :message, :string, 2
      optional :status, :string, 3
    end
    add_message "pckg_received_message.Cursor" do
      optional :index, :string, 1
      optional :position, :string, 2
    end
    add_message "pckg_received_message.ReceivedMessage" do
      optional :name, :string, 1
      optional :namespace, :string, 2
      optional :cursor, :message, 3, "pckg_received_message.Cursor"
    end
    add_message "pckg_received_message.CancelMessage" do
      optional :task_id, :string, 1
    end
  end
end

module PckgReceivedMessage
  RequestAck = Google::Protobuf::DescriptorPool.generated_pool.lookup("pckg_received_message.RequestAck").msgclass
  Cursor = Google::Protobuf::DescriptorPool.generated_pool.lookup("pckg_received_message.Cursor").msgclass
  ReceivedMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("pckg_received_message.ReceivedMessage").msgclass
  CancelMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("pckg_received_message.CancelMessage").msgclass
end
